version: "3.8"

services:


  db:
    image: mysql:8.0
    container_name: futbol-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_futbol
    ports:
      - "3307:3306"  
    volumes:
      - ./script_base_datos_sin_comentarios.sql:/docker-entrypoint-initdb.d/init.sql
      - futbol_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: futbol-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  futbol_db_data:
